[tool.poetry]
name = "protobuf-fun"
version = "0.1.0"
description = ""
authors = ["Mike Zimin <mikeziminio@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
protobuf = "4.21.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
